name: Tests
on: [push]

jobs:

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:

      - name: Install GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          go mod download

      - name: Run tests
        run: |
          go install get -v github.com/mfridman/tparse/...
          go test -race ./... -v -short -coverprofile=coverage.txt -covermode=atomic -json | tparse -all -notests -dump